apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: krishsrivastava/auth
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata: 
  name: auth-cluster-srv
spec:
  selector:
    app: auth
  ports: 
    - name: auth-cluster-srv
      protocol: TCP
      port: 3000
      targetPort: 3000
