apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: krishsrivastava/orders
          env:
            - name: NATS_URL
              value: nats://nats-srv:4222
            - name: MONGO_URI
              value: mongodb://orders-mongo-cluster-srv:27017/orders
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata: 
  name: orders-cluster-srv
spec:
  selector:
    app: orders
  ports: 
    - name: orders-cluster-srv
      protocol: TCP
      port: 3000
      targetPort: 3000
